# Generated by Django 2.1.1 on 2019-06-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_requestvideo_date_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestvideo',
            name='date_request',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
