# Generated by Django 2.1.1 on 2019-06-26 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20190626_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestvideo',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 22, 40, 29, 345703)),
        ),
    ]
