# Generated by Django 2.1.1 on 2019-06-27 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_auto_20190626_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestvideo',
            name='email',
            field=models.EmailField(default='aa@a.ru', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestvideo',
            name='date_request',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 27, 18, 32, 54, 710937)),
        ),
    ]
